:sparkles: Repurpose report post modal and re-use for list reporting
bluesky-social/social-app pull request #1070
Opened 2023-07-27 22:44 UTC by foysalit

I am not sure if the contextual options (spam, copyright violation etc.) all applies to both list and post but generally speaking, I think having a default/fallback modal for reporting any kind of content could be beneficial. This PR generalizes the report-post modal a bit to make it also report lists but still needs a once-over to make sure types and language are good!

https://github.com/bluesky-social/social-app/assets/1919066/5ae6d636-778b-4c5b-a5b6-8ac1a93d32e9

2023-07-28 16:02 UTC, pfrazee requested changes
If we want to repurpose the `ReportPostModal`, we should make its semantics generic (`ReportContent`). The parameters should then be changed to `uri` and `cid`.

You can intuit what kind of content it is by looking at the `uri` by parsing with the `AtUri` library (from the api) and then looking at the `parsedUri.collection` property, dropping the need for a `collection` parameter. From there you can tune the copy and the reporting options based on its value.

2023-07-28 16:05 UTC, foysalit commented
@pfrazee  Agreed! it was kinda hastily put together as a PoC and check if we want to take this direction. If you're onboard, I will make a pass through the semantics and may be even unify report account thing under this one report-content modal.

2023-07-28 16:20 UTC, pfrazee commented
SGTM!

2023-08-10 23:08 UTC, foysalit commented on .eslintrc.js
> +    'bskyweb',
was getting lint error trying to commit after conflict resolution.

2023-08-10 23:09 UTC, foysalit commented on src/view/com/modals/report/Modal.tsx
> +        selectedIssue={issue}
Without this, when you go to details input field and come back to the list, the previously selected reason disappears even though, in state, it still has that reason selected, just not showing in the UI.

2023-08-10 23:09 UTC, foysalit commented on src/view/index.ts
> +    faList,
This fixes list icon rendering on web under dropdown menus

2023-08-11 23:40 UTC, foysalit commented on __e2e__/tests/mute-lists.test.ts
> +    await element(by.id('selector-3')).tap()
I am now seeing the `Media` tab on `selector-2` so updating to 3 here which makes the test pass.

2023-08-11 23:42 UTC, foysalit commented on src/view/com/modals/report/ReasonOptions.tsx
> +const CommonReasons = {
Primary goal with this refactor is to kinda split data from the UI. Going forward, adding new reasons to existing or new collections should be relatively easier with this model.

2023-08-15 21:28 UTC, pfrazee approved these changes
🚀 Good update! Thanks for factoring in the changes I requested

2023-08-15 21:32 UTC, merged