HomeMenuItem goes above SearchMenuItem in a sessioned Drawer
bluesky-social/social-app pull request #4180
Opened 2024-05-23 00:53 UTC by jcsalterego

Unsure if this is wanted but in a Drawer with a session, move Home to the top to be consistent with other navigation menus.

### Before

![before](https://github.com/bluesky-social/social-app/assets/30475/d4ab3cc9-0b8f-404d-9655-7f0d4c735554)

### After

![after](https://github.com/bluesky-social/social-app/assets/30475/a29c78de-96d7-4b19-96b3-fcfe9c66e1df)

2024-05-23 02:22 UTC, haileyok approved these changes
Yea, that looks like an error when changing the icons. Thanks.

Edit: Actually, maybe it isn't...let me find out.

2024-05-23 15:59 UTC, mozzius commented
Yeah other apps often have search at the top?

2024-05-23 18:04 UTC, haileyok requested changes
Removing approval for now just so we can talk about this tomorrow.

2024-05-23 21:37 UTC, jcsalterego commented
_Sits in the waiting room, flips through_ Poster's Monthly _Magazine_

2024-06-07 16:37 UTC, jcsalterego commented
It works now for some reason(?). I am closing this PR

2024-06-07 16:37 UTC, closed without merging