remove resolution from post thread
bluesky-social/social-app pull request #4297
Opened 2024-05-31 07:48 UTC by haileyok

## Why

In the continuous effort to remove waterfalls, we can now remove these requests from `getPostThread`. To do so however, we need to do a little bit of reworking on how we pull already-loaded posts from the cache.

Currently we load the posts from the cache just based off of their URI. However, since we now are not going to have the resolved URI, we instead need to check both the handle and the rkey instead in our various `findAllPostsInQueryData` functions. This is a pretty straight forward change, though it adds a little extra logic.

## Test Plan

Note in the debugger that there are no more requests for DID resolutions when opening a post on a fresh load. Also note that whenever you open a post from these areas, there is no spinner:

- Feed
- Profile
- Search page
- Notifications

2024-05-31 10:12 UTC, mozzius approved these changes
good stuff

2024-05-31 12:16 UTC, gaearon commented on src/state/queries/notifications/feed.ts
> +          quotedPost.uri.endsWith(atUri.rkey)
This feels complicated. Ok but wondering if there are easier ways. I do think we need to pull this into a utility though cause the copy pasta is not obvious.

2024-05-31 12:17 UTC, gaearon commented on src/state/queries/notifications/feed.ts
> +          quotedPost.uri.endsWith(atUri.rkey)
Let's at least extract `isSamePostUri` or something

2024-05-31 12:17 UTC, gaearon requested changes
- let's reduce duplication of the URI check (it's non-trivial)
- placeholders are broken

2024-05-31 15:54 UTC, haileyok commented
@gaearon can you check now if placeholders work? I can't repro the spinner even off the first commit and still can't, so not sure what happened there? Left a video on Slack.

2024-06-03 22:58 UTC, gaearon approved these changes

2024-06-03 22:58 UTC, merged