Composer - replace threadgate modal with alf dialog
bluesky-social/social-app pull request #4329
Opened 2024-06-03 09:17 UTC by mozzius

<table>
  <tr>
    <td>iOS default</td>
    <td>iOS with selections</td>
    <td>Web</td>
  </tr>
  <tr>
    <td><img src="https://github.com/bluesky-social/social-app/assets/10959775/99af8ceb-1cc5-4438-b326-b8f704c1cddb" alt="Simulator Screenshot - iPhone 15 - 2024-06-03 at 12 08 44" width="200"></td>
    <td><img src="https://github.com/bluesky-social/social-app/assets/10959775/656fa4d4-29c3-45ee-adf9-074275830100" alt="Simulator Screenshot - iPhone 15 - 2024-06-03 at 12 08 50" width="200"></td>
    <td><img alt="Screenshot 2024-06-03 at 12 15 16" src="https://github.com/bluesky-social/social-app/assets/10959775/7d85ec79-5423-44a1-a99f-70a2f5c8fcd0" width="300"></td>
  </tr>
</table>

2024-06-04 10:55 UTC, gaearon commented
Pressing Escape now tries to dismiss both dialogs (previously it was ignored). We need to fix this to only dismiss the inner one (like with GIF picker).

2024-06-04 11:00 UTC, gaearon commented
also getting this weird spinner

![Screenshot 2024-06-04 at 11 59 56](https://github.com/bluesky-social/social-app/assets/810438/a9e4b5a3-809c-42af-9c1c-c6963869b123)

2024-06-04 11:02 UTC, mozzius commented
That's it loading your lists, maybe we should change the layout so that it's less janky

2024-06-04 11:25 UTC, gaearon commented
nah, it never loads. just stuck like this. there also no new network requests.

on main, there's no spinner.

2024-06-04 11:27 UTC, gaearon requested changes
- need to fix Escape handling
- distinguish no lists vs loading lists

2024-06-04 11:28 UTC, mozzius commented on src/view/com/composer/threadgate/ThreadgateBtn.tsx
> +          {lists?.length ? (
Oh whoops, missed that that was how it was doing that. Will fix

2024-06-04 14:11 UTC, gaearon commented
The height is jumping when changing selection, probably due to borders appearing and disappearing:

https://github.com/bluesky-social/social-app/assets/810438/b842b4fc-da16-42fd-be9d-c23d543ff617

It would be good to stabilize those.

Also, I'm not a big fan of using the same color for selection and the primary action:

![Screenshot 2024-06-04 at 15 00 05](https://github.com/bluesky-social/social-app/assets/810438/f989c0a1-982f-4132-b6ae-86f23c4b8889)

Let's do a pass over these before getting it in.

2024-06-24 18:35 UTC, pfrazee commented
Updated the buttons

|one|two|
|-|-|
|![CleanShot 2024-06-24 at 11 34 13@2x](https://github.com/bluesky-social/social-app/assets/1270099/9eab60a2-49a4-41c6-a51f-775174252863)|![CleanShot 2024-06-24 at 11 34 39@2x](https://github.com/bluesky-social/social-app/assets/1270099/50952bd3-f759-4001-a1da-eea1000ca403)|

2024-06-24 20:09 UTC, surfdude29 commented on src/components/WhoCanReply.tsx
> +      Toast.show('Thread settings updated')
Sorry to jump in, could the toast here and on L115 be marked for localization please? 🙏

2024-06-24 21:18 UTC, pfrazee commented
@gaearon Interesting, is that 2-states solution preferable to using an effect?

2024-06-24 21:23 UTC, gaearon commented
yeah, it avoids a "roundtrip", see here https://react.dev/reference/react/useState#storing-information-from-previous-renders :

>This pattern can be hard to understand and is usually best avoided. However, it’s better than updating state in an effect. When you call the set function during render, React will re-render that component immediately after your component exits with a return statement, and before rendering the children. This way, children don’t need to render twice. The rest of your component function will still execute (and the result will be thrown away). If your condition is below all the Hook calls, you may add an early return; to restart rendering earlier.

however i think i'll actually move the state down so that it gets torn down on dialog close

2024-06-24 21:48 UTC, pfrazee approved these changes
Excellent work @mozzius @gaearon

2024-06-24 22:15 UTC, gaearon approved these changes

2024-06-24 22:15 UTC, merged