Allow search params when converting bsky.app urls
bluesky-social/social-app pull request #4574
Opened 2024-06-19 18:50 UTC by mozzius

Allows linking to specific searches, i.e. https://bsky.app/profile/jgarplind.bsky.social/post/3kuyshu7heu2a

2024-06-19 20:44 UTC, gaearon commented on src/lib/strings/url-helpers.ts
> +      return urlp.pathname + urlp.search
I'm not sure this is a safe change — some code calling `convertBskyAppUrlIfNeeded` assumes there's no search. What do you think of the callsites? Could make a separate function for the case of handling in-app links. Or could return a richer data structure and let the caller decide which parts to use.

2024-06-19 22:26 UTC, gaearon commented
Doesn't seem to fix it for native btw

2024-06-19 22:33 UTC, gaearon requested changes
Looks like this would fix it for web but it still doesn't work on native. I think for native we might want to have a pushable version of the Search. This might be useful in other places too, like for searches themselves. Let's maybe leave this for now.

2024-06-20 13:03 UTC, mozzius commented
I wish we were using Expo Router, this would *just work*

2024-06-20 22:13 UTC, haileyok commented
Don't we just need to add `Search` into `commonScreens` instead of only being inside the `Search` tab? @mozzius

2024-06-20 22:23 UTC, pfrazee commented
I'll take a stab at it

2024-10-02 22:56 UTC, closed without merging