Renaming the Follow button to "Follow back" when followed by user
bluesky-social/social-app pull request #5281
Opened 2024-09-11 22:55 UTC by wscld

Hi there! 👋 I’d like to suggest a small improvement:
Rename the “Follow” button to “Follow back” when the user is already followed by someone, similar to how Instagram handles it? I think this would make it more intuitive for users to follow each other back.

Before:
<img width="601" alt="Screenshot 2024-09-11 at 19 44 04" src="https://github.com/user-attachments/assets/509117a4-1836-46fd-9de0-44335b653ab3">
After:
<img width="601" alt="Screenshot 2024-09-11 at 19 43 41" src="https://github.com/user-attachments/assets/51104e2b-4bf6-4fdb-ba99-d5f62c100b27">
Before:
<img width="601" alt="Screenshot 2024-09-11 at 19 43 09" src="https://github.com/user-attachments/assets/8008ded8-ef47-44c0-a643-e2ea65d189c8">
After:
<img width="601" alt="Screenshot 2024-09-11 at 19 42 17" src="https://github.com/user-attachments/assets/de192953-0f50-42e3-b72f-3844d81d2b97">

2024-09-11 23:52 UTC, surfdude29 commented
The button is already shown as **Follow Back** on a post from someone who follows you but who you don't follow as a result of the experiment in #3439, which has now been rolled out completely.

So I think this is a good suggestion as it would mean the button would appear as **Follow Back** on the user's profile and in other places too.

2024-09-12 00:08 UTC, gaearon requested changes
we should reuse existing translation for this, i think you want to tweak it to say `Follow Back` (which has already been translated). also i'm not sure putting conditions _inside_ the translation tag makes sense, i think you need to change it the other way around

2024-09-12 02:57 UTC, wscld commented
hey @gaearon @surfdude29 thanks for the feedback, makes sense to me! just commited the adjustments

2024-09-12 14:58 UTC, gaearon approved these changes

2024-09-12 14:59 UTC, merged