Add profile hover cards to more screens
bluesky-social/social-app pull request #6453
Opened 2024-11-17 12:01 UTC by bdbch

This PR adds ProfileHoverCards to the following screens:

- Notifications (On the first author & on each authors names in an expanded notification)
- Starter Pack profile list
- Starter Pack wizard profile list

Specially inside the Starter Pack wizard it was really hard to quickly see who a person is because you also couldn't open a profile in a new tab from there. This should help to quickly see what person you're adding to your Starter Pack.

2024-11-22 02:21 UTC, bdbch commented
Looking forward for feedback on this. I'd love to see more profile cards in a few places (as described above).

2024-11-23 17:42 UTC, gaearon commented
- Notification: Makes sense, if this was a separate PR I'd just merge that in.
- Starter Pack: Doesn't make sense to me, it's very duplicative. Would be better to extend the rows if we really need to.
- Starter Pack Wizard: I'm not sure it's worth doing it there. It doesn't work very well because it listens to the wrong scroll target, so it doesn't dismiss on scroll. This would have to be fixed. Still, what we *should* fix there is opening in a new tab.

2024-11-23 17:44 UTC, gaearon requested changes
let's do it just in notifications. and let's instead fix starter pack wizard to use links / open in new tab

2024-11-23 21:18 UTC, bdbch commented
Sure thing, will do. Should I look into linking for new tabs for starter packs in a new PR?

2024-11-24 17:57 UTC, gaearon commented
>Should I look into linking for new tabs for starter packs in a new PR?

Yea probably best to separate.

2024-11-24 18:04 UTC, bdbch commented
Reverted my changes made to the starter pack wizard & the profile card component, but want to fix the anchor for the profile card. Right now the position is a bit off. Will update when I'm done.

![image](https://github.com/user-attachments/assets/a3d2f453-ca75-437b-9cdc-47a02b0ee810)

2024-11-24 18:13 UTC, bdbch commented
Done! 👍

2025-01-03 01:44 UTC, bdbch commented
Happy new year!

Anything I could do to move this PR forward?

2026-01-20 10:17 UTC, bdbch commented
Already a year! Anything I can do to make progress on the PR? Otherwise I'd close it fit it's no longer needed.

2026-05-30 10:45 UTC, closed without merging

2026-05-30 10:46 UTC, bdbch commented
Closing this for now - feel free to take over if wanted.