#6861: Use available space to make focus on Composer TextInput easier
bluesky-social/social-app pull request #7207
Opened 2024-12-20 09:45 UTC by GrizliK1988

Fixes issue #6861  that is also reproducible on Android and iOS and this PR provides a for Web + Native.

### What this fix does?

Essentially the same thing for Web and Native: utilize display flex to make TextInput to take full available height.

### Web Before and After (Desktop)

**New Post TextInput area before:** 
<img width="1090" alt="image" src="https://github.com/user-attachments/assets/e8f4bf4d-357e-4bb8-b79b-941fc5fa69a8" />

**New Post TextInput area after:** 
<img width="1393" alt="image" src="https://github.com/user-attachments/assets/04f08190-34ec-4f2b-bdbb-32b2ff5f93e3" />

**Reply TextInput area before:** 
<img width="1076" alt="image" src="https://github.com/user-attachments/assets/30f484b9-fc7a-44aa-ae67-0318cc408427" />

**Reply TextInput area after:** 
<img width="1420" alt="image" src="https://github.com/user-attachments/assets/b2d28523-6479-40dd-b84d-58d03d6c1148" />

### Web Before and After (Mobile)

**New Post TextInput area before:** 
<img width="525" alt="image" src="https://github.com/user-attachments/assets/97fc7398-8a96-4c05-a709-6e9a20b5d623" />

**New Post TextInput area after:** 
<img width="472" alt="image" src="https://github.com/user-attachments/assets/e53d4b0c-d740-4981-b69e-a97cad866c80" />

**Reply TextInput area before:** 
<img width="522" alt="image" src="https://github.com/user-attachments/assets/e4cff5b7-8f73-46f0-b5a9-927200da414e" />

**Reply TextInput area after:** 
<img width="506" alt="image" src="https://github.com/user-attachments/assets/b62ca10e-abde-42b7-81e1-891e51261e4f" />

### iOS Before and After

**New Post TextInput area before:** 
<img width="470" alt="image" src="https://github.com/user-attachments/assets/c08157b1-3f28-4485-b7ed-91be5b7fa89a" />

**New Post TextInput area after:** 
<img width="474" alt="image" src="https://github.com/user-attachments/assets/02f030e1-4e5c-45c4-8938-b0210642f0da" />

**Reply TextInput area before:** 
<img width="453" alt="image" src="https://github.com/user-attachments/assets/0dea0fb2-5221-4b34-a3cf-0e3a528c733a" />

**Reply TextInput area after:** 
<img width="478" alt="image" src="https://github.com/user-attachments/assets/15aa326b-f29d-4941-bbb2-ef69bc2799c1" />

### Android Before and After

**New Post TextInput area before:** 
<img width="463" alt="image" src="https://github.com/user-attachments/assets/32d521bc-af5e-4e84-8bca-b9f9fd30f57d" />

**New Post TextInput area after:** 
<img width="473" alt="image" src="https://github.com/user-attachments/assets/b848e254-7f77-4ddd-b14c-539be7e39af9" />

**Reply TextInput area before:** 
<img width="523" alt="image" src="https://github.com/user-attachments/assets/bcec46ce-8d2d-41a4-a910-d5a6849ac047" />

**Reply TextInput area after:** 
<img width="475" alt="image" src="https://github.com/user-attachments/assets/d8a4160f-afd3-4c1f-a7e2-982be28015c8" />

2024-12-20 09:50 UTC, gaearon commented
Oh thanks! Last time I tried to do this I ran into some difficulty. Will give this a go.

2025-01-08 20:29 UTC, c960657 commented
I wasn't aware of this PR when I filed #7248.

My fix does not address Native, so I think this approach is better.

2025-01-21 00:34 UTC, gaearon commented
OK, so one problem with this approach is this case:

<img width="361" alt="Screenshot 2025-01-21 at 00 33 42" src="https://github.com/user-attachments/assets/0580fed1-e523-47e1-ad8a-d085f7d6ff75" />

We want the text box to hug the last line of the text instead.

2025-01-21 00:39 UTC, gaearon requested changes
need to fix the case where you have embeds

2025-01-21 06:46 UTC, GrizliK1988 commented
Thanks for testing! Let me have a look

2025-02-24 20:00 UTC, gaearon commented
@mozzius

2025-02-24 20:19 UTC, GrizliK1988 commented
Just realized that I missed to add a comment related to last changes.

Web: no changes needed because Composer component is in a modal and it has enforced min height in absolute value.

Native: here changes are still needed and implemented. Initial implementation was wrong because it blocked text input growth in height (and broke embeds styling with it). Current approach works well with embeds and keeps text input expansion in height. 

Why padding top changed: to avoid screen jump when keyboard is hidden. Keyboard hide causes layout change and padding top somehow causes jump in 4 pixels up for a moment and then padding appears again.

2025-02-25 12:24 UTC, mozzius commented
Moved to https://github.com/bluesky-social/social-app/pull/7836 so I could rebase it off of main - thank you so much for your great work though! Huge improvement!

2025-02-25 12:24 UTC, closed without merging

2025-02-25 12:39 UTC, GrizliK1988 commented
Thanks a lot for the great social app and for reviewing/testing :)