Align lightbox status bar behaviour on Android 15 with iOS
bluesky-social/social-app pull request #7222
Opened 2024-12-20 19:52 UTC by mozzius

Now that we have edge to edge mode, we can do what I always intended to do: hide the system bar with the other lightbox controls, like how iOS works

https://github.com/user-attachments/assets/6c82d96e-2450-48b2-8622-86016a436b6e

2024-12-20 20:30 UTC, gaearon requested changes
causes white flash on the bottom bar on my android 12

2024-12-20 20:31 UTC, mozzius commented
Let's put this on ice until we can figure it out. it's not urgent

2025-01-19 13:47 UTC, zoontek commented
It occurs because `expo-navigation-bar` is setting an opaque background, and the update doesn't occur in sync. By truly going edge-to-edge (transparent nav bar), there's no issue:

https://github.com/user-attachments/assets/a7a2508f-0db0-4d81-95f7-7562c0c17734

2025-01-19 13:47 UTC, zoontek commented
Preliminary work is here: https://github.com/bluesky-social/social-app/pull/7497

2025-05-03 18:16 UTC, closed without merging