Various case and text fixes.
bluesky-social/social-app pull request #757
Opened 2023-05-19 18:50 UTC by alimony

This fixes some consistency issues with text cases on labels (https://github.com/bluesky-social/social-app/issues/709) and includes a few other tiny text polish fixes. I will make line comments in this PR to clarify a few things.

2023-05-19 18:51 UTC, alimony commented on src/view/com/modals/AddAppPasswords.tsx
This seems like a jumble of two different versions, I used the one used elsewhere in the app.

2023-05-19 18:52 UTC, alimony commented on src/view/com/modals/DeleteAccount.tsx
> +              your email address.
Wording seems clearer to me.

2023-05-19 18:52 UTC, alimony commented on src/view/screens/SearchMobile.tsx
> +                    Search for users and posts on the network
To clarify this searches for both users and posts.

2023-05-19 18:53 UTC, alimony commented on src/view/screens/Settings.tsx
> +              Delete my account…
To follow the convention of system menu items etc. where ellipsis means there will be further prompts before any action is actually taken.

2023-05-30 20:14 UTC, ansh requested changes
Mostly looks good. Have a few changes.

2023-05-30 20:14 UTC, ansh commented on src/view/com/auth/SplashScreen.web.tsx
> +                Create a New Account
Can we keep this lowercase?

2023-05-30 20:14 UTC, ansh commented on src/view/com/auth/SplashScreen.tsx
> +                Create a New Account
Can we keep this lowercase?

2023-05-30 20:14 UTC, ansh commented on __e2e__/tests/home-screen.test.ts
> +    await element(by.id("homeScreenFeedTabs-What's Hot")).tap()
Let's revert this for now

2023-05-30 20:14 UTC, ansh commented on src/view/com/modals/AddAppPasswords.tsx
> +          Can only contain letters, numbers, spaces, dashes, and underscores.
Good catch! Thanks :)

2023-05-30 20:14 UTC, ansh commented on src/view/shell/desktop/RightNav.tsx
> +            text="Privacy policy"
Let's revert this for now.

2023-05-30 20:14 UTC, ansh requested changes
Mostly looks good. Have a few changes.

2023-06-01 00:33 UTC, ansh commented
@alimony Fixed lint errors on main. Feel free to merge main into this branch to re-runt he tests.

2023-06-01 01:11 UTC, alimony commented
@ansh Done and passing!

2023-06-08 19:47 UTC, alimony commented
@ansh This is still waiting for approval after making your requested changes.

2023-06-13 18:35 UTC, ansh approved these changes
LGTM. Thanks for the PR!

2023-06-13 18:35 UTC, merged